# Generated by Django 4.0.4 on 2022-05-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poast',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cmpny_code', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('in_date', models.DateTimeField()),
            ],
        ),
    ]
