# Generated by Django 4.0.4 on 2022-05-10 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techBlogPosts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poast',
            new_name='Post',
        ),
    ]
